package me.fzzyhmstrs.amethyst_imbuement.material

import me.fzzyhmstrs.amethyst_imbuement.AI
import net.fabricmc.yarn.constants.MiningLevels

object AiToolMaterialsConfig{
    val GARNET = ValidatedToolMaterial.Builder()
        .durability(3151)
        .miningSpeedMultiplier(7.5f)
        .attackDamage(3f)
        .miningLevel(3)
        .enchantability(12)
        .repairIngredient(AI.identity("garnet"))
        .build()
    val GLOWING = ValidatedToolMaterial.Builder()
        .durability(333)
        .miningSpeedMultiplier(11.5f)
        .attackDamage(4.5f)
        .miningLevel(MiningLevels.NETHERITE)
        .enchantability(12)
        .repairIngredient(AI.identity("glowing_fragment"))
        .build()
    val STEEL = ValidatedToolMaterial.Builder()
        .durability(400)
        .miningSpeedMultiplier(6.5f)
        .attackDamage(2.5f)
        .miningLevel(2)
        .enchantability(15)
        .repairIngredient(AI.identity("steel_ingot"))
        .build()
    val AMETRINE = ValidatedToolMaterial.Builder()
        .durability(2550)
        .miningSpeedMultiplier(9.5f)
        .attackDamage(5f)
        .miningLevel(MiningLevels.NETHERITE)
        .enchantability(18)
        .repairIngredient(AI.identity("ametrine"))
        .build()
    val GLISTERING = ValidatedToolMaterial.Builder()
        .durability(550)
        .miningSpeedMultiplier(9.5f)
        .attackDamage(11f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(15)
        .repairIngredient(AI.identity("garnet"))
        .build()
}